apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  # Username: admin (base64 encoded)
  username: YWRtaW4=
  # Password: password123 (base64 encoded)
  # IMPORTANT: Change this in production!
  password: cGFzc3dvcmQxMjM=
