apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # JWT Secret: super-secret-jwt-key-change-this (base64 encoded)
  # IMPORTANT: Change this in production!
  jwt-secret: c3VwZXItc2VjcmV0LWp3dC1rZXktY2hhbmdlLXRoaXM=
