name: Build Docker Images (Local Testing)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [product-service, user-service, order-service, api-gateway]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./${{ matrix.service }}
        push: false
        tags: ${{ matrix.service }}:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
